[build]
  publish = "."
  command = "echo 'Forzando reconstrucción'"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 